### ISSUE TITLE
Gulp default task hangs

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback-example-pubsub#3]
It does not quit

**Comment by superkhau** [comment]
Confirmed. Would you like to submit a patch?

**Comment by superkhau** [comment]
@0candy Reassigning to you since you are the repo expert.

**Comment by pktippa** [comment]
We can close this issue since the pull #14 is accepted and merged.

**Comment by 0candy** [comment]
Fixed merged, closing this issue.
