### ISSUE TITLE
Shitty example

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback-example-pubsub#5]
This should probably be a private repository until it is better documented and has some kind of functionality. It is misleading and a timesink in its current state.

**Comment by jakerella** [comment]
While we appreciate community feedback, the title of this comment is inappropriate and not appreciated. This is a demo repo, not a full application, and not the library it is intended to demonstrate. As such, it will remain as is.

**Comment by kennethlynne** [comment]
Sorry for the wording. I did miss some more information in the readme about how this can be used, and it did not run in any way locally, and thus it is probably worth looking into how this can be more helpful

**Comment by jakerella** [comment]
Thanks for the update. I agree this is not documented well, we should have a better example, but that's just not high on our priority list right now. If we're lucky, @crandmck can update the readme with some better information on how to use this example app, and what it does (and why). There are some [additional docs on our web site](http://docs.strongloop.com/display/MSG/Pub-sub), which we should probably link to from here.

**Comment by crandmck** [comment]
I'll try to find time to improve these and the pub-sub docs in general, but @jakerella is correct that this is not a top priority.  I did at least add links in the README to the other relevant docs.
